apiVersion: apps/v1
kind: Deployment
metadata:
  name: acme-app
  labels:
    app: acme
spec:
  replicas: 3
  selector:
    matchLabels:
      app: acme
  template:
    metadata:
      labels:
        app: acme
    spec:
      containers:
         - name: acme-container
            image: acmeimage:latest
            ports:
         - containerPort: 8080
